version: '3.8'
services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib
    command:
      - "--config=/etc/otel-collector.yml"
    volumes:
      - ./otel/otel-collector.yml:/etc/otel-collector.yml
    ports:
      - "4317:4317" # OTLP gRPC receiver
      - "4318:4318" # OTLP http receiver
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension
      - "8889:8889" # serve prometheus metrics
  grafana:
    image: grafana/grafana
    environment:
      GF_AUTH_DISABLE_LOGIN_FORM: true
      GF_AUTH_ANONYMOUS_ENABLED: true
      GF_AUTH_ANONYMOUS_ORG_ROLE: Admin
    volumes:
      - grafana-data:/var/lib/grafana
    ports:
      - "3000:3000"
  bootelemetry-metrics:
    image: gustavo-flor/bootelemetry-metrics
    build: .
    command:
      - "-Dotel.exporter.otlp.endpoint=http://otel-collector:4317"
    ports:
      - "8080:8080" # serve api
volumes:
  grafana-data:
    external: false
